# MLDemoBundle routes (to be removed)
_demo:
    resource: "@MLDemoBundle/Controller/"
    type:     annotation
    prefix:   /

hydra:
    resource: "@HydraBundle/Controller/"
    type:     annotation
    prefix:   /
