_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

# MLDemoBundle routes (to be removed)
_demo:
    resource: "@MLDemoBundle/Controller/"
    type:     annotation
    prefix:   /

_main:
    resource: routing.yml
