security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        ML\DemoBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        demo:
            entity: { class: MLDemoBundle:User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~
            http_basic:
               realm: "Hydra Demo"
            stateless:  true

    access_control:
        - { path: ^/issues/, roles: ROLE_USER, methods: [ POST, PUT, DELETE ] }
        - { path: ^/comments/, roles: ROLE_USER, methods: [ POST, PUT, DELETE ] }
